export type EducationPractitionerProfile = {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  website: string | null;
  trainingProgram: string | null;
  graduationYear: string | null;
  languages: string[];
  practiceFocuses: string[];
  addressLines: string[];
  city: string;
  country: string;
  latitude: number | null;
  longitude: number | null;
};

export const EDUCATION_PRACTITIONERS: EducationPractitionerProfile[] = [
  {
    id: "406",
    name: "Margo Arts",
    email: "margo6arts@gmail.com",
    phone: "0467068591",
    website: "https://dehelpendehand.be",
    trainingProgram: "Lindau",
    graduationYear: "2016",
    languages: ["English", "French", "Dutch", "German"],
    practiceFocuses: ["Reeducation", "Aging Well", "Babies & Children", "Neurological Issues", "Animals"],
    addressLines: ["Smettert 6", "3930 Hamont", "Belgium"],
    city: "Hamont",
    country: "Belgium",
    latitude: 51.2512315,
    longitude: 5.5454386,
  },
  {
    id: "390",
    name: "Klaas Overzee",
    email: "info@lifemoves.me.uk",
    phone: "07436016688",
    website: "http://LifeMoves.UK",
    trainingProgram: "London",
    graduationYear: "1990",
    languages: ["English"],
    practiceFocuses: ["Learning & Creativity"],
    addressLines: ["3 College", "Bovey Tracey, Newton Abbot, Teignbridge TQ13 9EW", "United Kingdom"],
    city: "Newton Abbot",
    country: "United Kingdom",
    latitude: 50.5296441,
    longitude: -3.6112097,
  },
  {
    id: "384",
    name: "Heidi Carlsen",
    email: "hbcarlsen@gmail.com",
    phone: "3478535854",
    website: null,
    trainingProgram: "New York City",
    graduationYear: "2013",
    languages: ["English", "Danish"],
    practiceFocuses: ["Reeducation", "Chronic Pain", "Performing Arts"],
    addressLines: ["1199 Sanchez Street", "San Francisco 94114", "United States"],
    city: "San Francisco",
    country: "United States",
    latitude: 37.7879363,
    longitude: -122.4075201,
  },
  {
    id: "383",
    name: "Sandra Ortega Bejarano",
    email: "sandra@feldenkraissevilla.es",
    phone: "0034656629088",
    website: "https://feldenkraissevilla.es/",
    trainingProgram: "Madrid",
    graduationYear: "2021",
    languages: ["English", "French", "Spanish"],
    practiceFocuses: ["Reeducation", "Chronic Pain", "Aging Well", "Performing Arts", "Personal Development", "Learning & Creativity"],
    addressLines: ["Antonio Filpo Rojas,16 2", "Sevilla 41008", "Spain"],
    city: "Seville",
    country: "Spain",
    latitude: 37.3886303,
    longitude: -5.9953403,
  },
  {
    id: "364",
    name: "Jill Wigmore-Welsh",
    email: "jill@wigmore-welsh.com",
    phone: "07885467466",
    website: "https://jillwigmorewelsh.com",
    trainingProgram: "Lewis2 UK",
    graduationYear: "1999",
    languages: ["English"],
    practiceFocuses: ["Aging Well"],
    addressLines: ["218 Tilehurst Road", "Reading RG30 2NE", "United Kingdom"],
    city: "Reading",
    country: "United Kingdom",
    latitude: 51.4514953,
    longitude: -0.9836342,
  },
  {
    id: "306",
    name: "Ieva Labanauskaitė",
    email: "feldenkrais.lietuva@gmail.com",
    phone: "+37062112060",
    website: "https://www.feldenkraislietuva.com/",
    trainingProgram: "Brussels 2",
    graduationYear: "2025",
    languages: ["English", "Lithuanian"],
    practiceFocuses: ["Chronic Pain", "Performing Arts", "Personal Development", "Psychological Challenges", "Learning & Creativity", "Neurological Issues"],
    addressLines: ["Saltoniškių g. 31", "Inmind studija, Vilnius", "Lithuania"],
    city: "Vilnius",
    country: "Lithuania",
    latitude: 54.6870458,
    longitude: 25.2829111,
  },
  {
    id: "327",
    name: "Olivia Shaffer",
    email: "ojshffr@gmail.com",
    phone: "6046165566",
    website: "https://www.klinikvancouver.com/olivia-shaffer",
    trainingProgram: "Kelowna Feldenkrais Teacher Training",
    graduationYear: "2024",
    languages: ["English"],
    practiceFocuses: ["Chronic Pain", "Aging Well", "Performing Arts", "Personal Development", "Other"],
    addressLines: ["4505 West 12th Ave.", "Vancouver V6R 2R4", "Canada"],
    city: "Vancouver",
    country: "Canada",
    latitude: 49.2608724,
    longitude: -123.113952,
  },
  {
    id: "317",
    name: "Ilse Gysel",
    email: "ilse@vavavoom.be",
    phone: "+32486164115",
    website: "https://www.vavavoom.be",
    trainingProgram: "Brussels",
    graduationYear: "2024",
    languages: ["English", "French", "Dutch"],
    practiceFocuses: ["Personal Development", "Psychological Challenges"],
    addressLines: ["Jakob van Ooststraat 10.01", "Brugge 8000", "Belgium"],
    city: "Brugge",
    country: "Belgium",
    latitude: 51.2085526,
    longitude: 3.226772,
  },
  {
    id: "311",
    name: "Catherine Delasalle",
    email: "catherine.delasalle@gmail.com",
    phone: "0032475661032",
    website: "https://lechantdupossible.be",
    trainingProgram: "Paris IV et V",
    graduationYear: "2001",
    languages: ["English", "French", "Dutch"],
    practiceFocuses: ["Chronic Pain", "Aging Well", "Performing Arts", "Personal Development", "Psychological Challenges", "Learning & Creativity"],
    addressLines: ["15 rue de la Filature", "Brussels 1060", "Belgium"],
    city: "Brussels",
    country: "Belgium",
    latitude: 50.8467372,
    longitude: 4.352493,
  },
  {
    id: "309",
    name: "Deniz Erdem",
    email: "erdem.den@gmail.com",
    phone: "+905343239010",
    website: null,
    trainingProgram: "Amsterdam International Teacher Training Program IV",
    graduationYear: "2016",
    languages: ["English", "Turkish"],
    practiceFocuses: ["Personal Development"],
    addressLines: ["Altinbilezik sk. no:10/5", "Beyoglu, Istanbul 34400", "Turkey"],
    city: "Istanbul",
    country: "Turkey",
    latitude: 41.006381,
    longitude: 28.9758715,
  },
  {
    id: "307",
    name: "Judith Radics",
    email: "j.radics@yahoo.de",
    phone: null,
    website: null,
    trainingProgram: "Lüdenscheid",
    graduationYear: "2020",
    languages: ["English", "German", "Hungarian"],
    practiceFocuses: [],
    addressLines: ["Meerfeldstr. 10", "Köln 50737", "Germany"],
    city: "Köln",
    country: "Germany",
    latitude: 50.938361,
    longitude: 6.959974,
  },
  {
    id: "304",
    name: "Bärbel Rücker",
    email: "baerbel.ruecker@gmail.com",
    phone: "++44 (0) 7474612701",
    website: "https://movingexperience.eu",
    trainingProgram: "Bern 2",
    graduationYear: "2017",
    languages: ["English", "German"],
    practiceFocuses: ["Aging Well", "Performing Arts", "Personal Development", "Sports & Martial Arts", "Learning & Creativity"],
    addressLines: ["The Flat, r/o The Old Bungalow, Gorsty Knoll", "Coleford GL16 7LR", "United Kingdom"],
    city: "Coleford",
    country: "United Kingdom",
    latitude: 51.7938786,
    longitude: -2.6183238,
  },
  {
    id: "298",
    name: "Joyce Allison",
    email: "voiceofjoyce@icloud.com",
    phone: "4254443175",
    website: null,
    trainingProgram: "Feldenkrais Training Academy with Jeff Haller in Seattle, WA USA",
    graduationYear: "2022",
    languages: ["English"],
    practiceFocuses: ["Chronic Pain", "Aging Well", "Performing Arts", "Learning & Creativity", "Neurological Issues"],
    addressLines: ["18431 61st Ave NE", "Kenmore 98028", "United States"],
    city: "Kenmore",
    country: "United States",
    latitude: 47.7596715,
    longitude: -122.2496367,
  },
  {
    id: "297",
    name: "Roana Salome Falkenberg",
    email: "mail@roana-salome.de",
    phone: "017662702766",
    website: "https://www.roana-salome.de/",
    trainingProgram: "Feldenkrais-Zentrum Chava Shelhav",
    graduationYear: "2023",
    languages: ["English", "French", "German"],
    practiceFocuses: ["Reeducation", "Performing Arts", "Personal Development", "Sports & Martial Arts", "Learning & Creativity"],
    addressLines: ["Wilhelm-Stolze-Straße 21", "Berlin 10249", "Germany"],
    city: "Berlin",
    country: "Germany",
    latitude: 52.5173885,
    longitude: 13.3951309,
  },
  {
    id: "388",
    name: "Anne Billant",
    email: "melodie.feldenkrais@gmail.com",
    phone: "06 88 10 82 24",
    website: null,
    trainingProgram: "Cantal 2",
    graduationYear: "2022",
    languages: ["French"],
    practiceFocuses: [],
    addressLines: ["176 boulevard de Charonne", "Paris 75020", "France"],
    city: "Paris",
    country: "France",
    latitude: 48.8588897,
    longitude: 2.320041,
  },
  {
    id: "377",
    name: "Julie Meftah",
    email: "j.meftah@yahoo.fr",
    phone: "0680234087",
    website: "https://www.feldenkrais-france.org/praticiens/julie-meftah",
    trainingProgram: "Cantal 3",
    graduationYear: "2023",
    languages: ["French"],
    practiceFocuses: [],
    addressLines: ["25 rue Principale", "Haselbourg 57850", "France"],
    city: "Haselbourg",
    country: "France",
    latitude: 48.6848839,
    longitude: 7.2036372,
  },
  {
    id: "365",
    name: "Lou Boillon Jacquard",
    email: "contact@louboillon.com",
    phone: "0679885557",
    website: "https://louboillon.com",
    trainingProgram: "Ifeld2",
    graduationYear: "2017",
    languages: ["French"],
    practiceFocuses: ["Chronic Pain", "Sports & Martial Arts"],
    addressLines: ["20 rue des Maires", "Saone 25660", "France"],
    city: "Saone",
    country: "France",
    latitude: 47.2249278,
    longitude: 6.1168858,
  },
  {
    id: "329",
    name: "Boryana Todorova",
    email: "boryana@feldenkrais.brussels",
    phone: "+32 485.00.13.55",
    website: "https://feldenkrais.brussels",
    trainingProgram: "Brussels 2",
    graduationYear: "2025",
    languages: ["English", "French", "Bulgarian"],
    practiceFocuses: [],
    addressLines: ["38, rue Fernand Gillion", "Brussels 1190", "Belgium"],
    city: "Brussels",
    country: "Belgium",
    latitude: 50.8467372,
    longitude: 4.352493,
  },
  {
    id: "326",
    name: "Nivea Loiselle",
    email: "nivealoiselle@gmail.com",
    phone: null,
    website: "https://www.nivealoiselle.com/",
    trainingProgram: "Méthode Feldenkrais Cantal 2",
    graduationYear: "2022",
    languages: ["English", "French", "Portuguese"],
    practiceFocuses: ["Reeducation", "Chronic Pain", "Aging Well", "Personal Development", "Neurological Issues"],
    addressLines: ["26 rue de Valserres", "Gap 05000", "France"],
    city: "Gap",
    country: "France",
    latitude: 44.5612032,
    longitude: 6.0820639,
  },
  {
    id: "325",
    name: "Christina Clar",
    email: "office@christinaclar.net",
    phone: "+43 664 3068870",
    website: "https://christinaclar.net/project/feldenkrais/",
    trainingProgram: "Barcelona International 3",
    graduationYear: "2024",
    languages: ["English", "French", "German"],
    practiceFocuses: ["Chronic Pain", "Performing Arts", "Learning & Creativity"],
    addressLines: ["Prebl 111", "Prebl 9461", "Austria"],
    city: "Prebl",
    country: "Austria",
    latitude: 46.9135854,
    longitude: 14.7975788,
  },
  {
    id: "324",
    name: "Reine Erlenbach",
    email: "reine.erlenbach@wanadoo.fr",
    phone: "06 72 70 26 20",
    website: null,
    trainingProgram: "IFELD III",
    graduationYear: null,
    languages: ["French", "German"],
    practiceFocuses: ["Psychological Challenges", "Other"],
    addressLines: ["7 grande Rue", "Chaux du Dombief 39150", "France"],
    city: "Chaux du Dombief",
    country: "France",
    latitude: 46.604661,
    longitude: 5.9035742,
  },
  {
    id: "321",
    name: "Cécile Riffont",
    email: "feldenkraisottignies@gmail.com",
    phone: "+32496/02.00.97",
    website: "https://feldenkraisottignies.be/",
    trainingProgram: "Bruxelles 1",
    graduationYear: "2022",
    languages: ["French"],
    practiceFocuses: ["Reeducation", "Chronic Pain", "Aging Well", "Work Environment"],
    addressLines: ["10 rue du viaduc", "Ottignies 1340", "Belgium"],
    city: "Ottignies",
    country: "Belgium",
    latitude: 50.666357,
    longitude: 4.5690502,
  },
  {
    id: "318",
    name: "Agnès Calmel",
    email: "agnescalmel@gmail.com",
    phone: "0660776084",
    website: null,
    trainingProgram: "Paris9",
    graduationYear: "2006",
    languages: ["English", "French"],
    practiceFocuses: ["Reeducation", "Chronic Pain", "Aging Well", "Performing Arts", "Personal Development", "Sports & Martial Arts", "Work Environment", "Learning & Creativity", "Neurological Issues"],
    addressLines: ["39 rue Didot", "Paris 75014", "France"],
    city: "Paris",
    country: "France",
    latitude: 48.8588897,
    longitude: 2.320041,
  },
  {
    id: "316",
    name: "Laure Taquet",
    email: "taquetlaure@yahoo.fr",
    phone: "0687168081",
    website: "https://yanomae.my.canva.site/",
    trainingProgram: "Brussels 2 (2021-2025)",
    graduationYear: "2025",
    languages: ["French"],
    practiceFocuses: [],
    addressLines: ["84 rue de la Chevalerie", "Tours 37100", "France"],
    city: "Tours",
    country: "France",
    latitude: 47.3900474,
    longitude: 0.6889268,
  },
  {
    id: "313",
    name: "Jenny Rombai",
    email: "jennyrombai@gmail.com",
    phone: "0477935361",
    website: "https://www.feldenkraisjennyrombai.net/",
    trainingProgram: "Barcelona International 2",
    graduationYear: "2022",
    languages: ["English", "French", "German", "Spanish", "Italian"],
    practiceFocuses: ["Aging Well", "Performing Arts", "Sports & Martial Arts"],
    addressLines: ["Av. Wielemans Ceuppens 101", "Brussels 1190", "Belgium"],
    city: "Brussels",
    country: "Belgium",
    latitude: 50.8467372,
    longitude: 4.352493,
  },
  {
    id: "305",
    name: "Babette Brédoire Loosfelt",
    email: "bredlos@free.fr",
    phone: "+33651538728",
    website: "https://www.feldenkrais.loostiic.fr/",
    trainingProgram: "Cantal 1",
    graduationYear: "2021",
    languages: ["French"],
    practiceFocuses: [],
    addressLines: ["11 rue du ruisseau", "Giou-de-Mamou 15130", "France"],
    city: "Giou-de-Mamou",
    country: "France",
    latitude: 44.9314821,
    longitude: 2.5116651,
  },
  {
    id: "303",
    name: "Béatrice Cuenot",
    email: "beatrice.cuenot@icloud.com",
    phone: "0609391566",
    website: null,
    trainingProgram: "Ifeld7",
    graduationYear: "2024",
    languages: ["French"],
    practiceFocuses: [],
    addressLines: ["124 rue du grand coin", "Saint Jean de Maurienne 73300", "France"],
    city: "Saint Jean de Maurienne",
    country: "France",
    latitude: 45.2775475,
    longitude: 6.345172,
  },
  {
    id: "299",
    name: "João Miguel Vaz Ribeiro",
    email: "joaomvribeiro@gmail.com",
    phone: "919623484",
    website: null,
    trainingProgram: "IF Lisboa 1",
    graduationYear: "2022",
    languages: ["English", "French", "Portuguese"],
    practiceFocuses: [],
    addressLines: ["Pátio da Rua Nova, entrada C, casa Q", "5000-652 Vila Real", "Portugal"],
    city: "Vila Real",
    country: "Portugal",
    latitude: 41.5229299,
    longitude: -7.5466312,
  },
];

export function getEducationPractitionerProfiles() {
  return EDUCATION_PRACTITIONERS;
}
